### ISSUE TITLE
Diseño del montacargas

### ISSUE THREAD

**Issue by RodrigoTeran** [RodrigoTeran/reto-multiagentes#1]
# Especificaciones
- [x] Terminar el modelo 3D [Figma](https://www.figma.com/file/65ujZDB3KdVLtgEDqPjRFh/Multiagentes?type=design&node-id=0%3A1&mode=design&t=n7eHldWztrexWC2G-1)
- [x] Agregar una textura diferente a cada pieza:
 - Techo
 - Cuerpo
 - La plataforma

**Comment by mateobv07** [comment]
![montecargars](https://github.com/RodrigoTeran/reto-multiagentes/assets/41759833/237e8c26-4bee-41a4-a764-ab8a04c7fcc0)

En vez de texturas quedo el profe que con colores esta bien verdad?
