### ISSUE TITLE
Refactorizar la rotación del robot

### ISSUE THREAD

**Issue by RodrigoTeran** [RodrigoTeran/reto-multiagentes#3]
# Especificaciones
- [x] [Refactorizar la rotación](https://github.com/RodrigoTeran/reto-multiagentes/blob/b65c7a6a0b3ee9508a7423ff30bf542c3b3571b2/Lift/Lift.py#L188)
- [x] Tiene que funcionar con vector
- [x] Tiene que rotar en dirección hacia una coordenada en específico (para direccionarse a la caja)

**Comment by a01276097** [comment]
listo dir a coordenada especifica
