### ISSUE TITLE
Movimiento del robot

### ISSUE THREAD

**Issue by RodrigoTeran** [RodrigoTeran/reto-multiagentes#5]
# Especificaciones
- [x] Que se puedan mover de manera lineal
- [x] Que el movimiento sea uniforme
- [x] Velocidad aleatoria

**Comment by HugoGoHe** [comment]
https://github.com/RodrigoTeran/reto-multiagentes/commit/4e0beda1bf1c8a3a1bdfd88b04f93fcdf660e27c#r137610717
